### ISSUE TITLE
VideoStreamTrack fails to start streaming in 3.0.0-pre.8 (worked fully stable on 3.0.0-pre.4, partial crash on pre.6)

### ISSUE THREAD

**Issue by merttalhayener** [Unity-Technologies/com.unity.webrtc#1085]
### Package version

3.0.0-pre.8

### Environment

```markdown
* OS:Android (HTC - Oculus VR Devices)
* Unity version:6000.0.49f1
```

### Steps To Reproduce

	1.	Create a Unity project (tested with Unity 6000.0.49f1).
	2.	Install com.unity.webrtc package with different versions: pre.4, pre.6, and pre.8.
	3.	Set up a simple video streaming scenario using VideoStreamTrack to stream a RenderTexture from VR device (Oculus/HTC Vive Focus, OpenXR, Vulkan backend).
	4.	Start WebRTC signaling and establish peer connection successfully.
	5.	Once the video stream starts, observe behavior on each version.

### Current Behavior

	•	✅ In 3.0.0-pre.4: Streaming works fully stable, video frames are continuously streamed, no crashes or rendering issues observed.
	•	⚠ In 3.0.0-pre.6: Streaming starts, first frames are correctly sent, but the application crashes after 1–5 seconds randomly. Sometimes crashes after first frame, sometimes after a few seconds.
	•	❌ In 3.0.0-pre.8: Streaming never starts, VideoStreamTrack creation fails immediately or rendering crashes instantly. In some cases, encoder context is not fully initialized before first frame delivery.

All versions successfully complete peer connection, signaling, and ICE negotiation. The problem is purely at the rendering/encoder binding level after the video streaming starts.

On Unity Editor all versions successfully complete peer connection, signaling, and ICE also **Video Streaming**. It seems like the problem comes with the version update only affects Android devices.

### Expected Behavior

	•	VideoStreamTrack should continue streaming frames consistently after the connection is established, without random crashes.
	•	Encoder binding should behave identically across all 3.x versions.
	•	New versions (pre.6 and later) should maintain compatibility with rendering stability that was working properly in pre.4.

### Anything else?

Issue fully reproduces even when using Unity Render Streaming package (which internally uses com.unity.webrtc as its core dependency).
	•	Same behavior is observed on Render Streaming package:
	•	When Render Streaming uses WebRTC 3.0.0-pre.8 or pre.6, identical crashes occur (either immediately or a few seconds after starting the video stream).
	•	After downgrading Render Streaming’s internal WebRTC package to 3.0.0-pre.4, streaming works fully stable.
	•	This strongly suggests the root cause is inside the WebRTC package itself, and affects any downstream solution that builds on top of it.

**Comment by merttalhayener** [comment]
> [@merttalhayener](https://github.com/merttalhayener) Is your graphics API set to Vulkan/Auto for Android?

Yes, in my project settings, “Auto Graphics API” is disabled, and Vulkan is explicitly selected as the Graphics API.

**Comment by himanchalsharmaa** [comment]
> > [@merttalhayener](https://github.com/merttalhayener) Is your graphics API set to Vulkan/Auto for Android?
> 
> Yes, in my project settings, “Auto Graphics API” is disabled, and Vulkan is explicitly selected as the Graphics API.

Then this is your culprit most probably. There's some issues with Vulkan Initialisation on Quest headsets.
Try OpenGL ES3(Multipass with MSAA or Singlepass without MSAA) and see if it works.

**Comment by himanchalsharmaa** [comment]
> > > > [@merttalhayener](https://github.com/merttalhayener) Is your graphics API set to Vulkan/Auto for Android?
> > > 
> > > 
> > > Yes, in my project settings, “Auto Graphics API” is disabled, and Vulkan is explicitly selected as the Graphics API.
> > 
> > 
> > Then this is your culprit most probably. There's some issues with Vulkan Initialisation on Quest headsets. Try OpenGL ES3(Multipass with MSAA or Singlepass without MSAA) and see if it works.
> 
> Actually, this is exactly what I was referring to when I initially opened the issue. Ideally, I shouldn’t need to make any changes on my side. Everything works flawlessly with Vulkan in version 3.0.0-pre.4, but just two versions later, the application sends a single frame and crashes—and in the latest version, no frame is transmitted at all.
> 
> I’ve tested this behavior on both Meta Quest and HTC Vive headsets, and the result is exactly the same on both platforms. So this is not limited to Quest-specific behavior.
> 
> This is something the development team should seriously consider, as many VR applications rely on Vulkan as their primary graphics API.

Have you tried the No Vulkan Hook project?
https://github.com/UCL-VR/unity-webrtc-no-vulkan-hook

**Comment by himanchalsharmaa** [comment]
> ### Package version
> 3.0.0-pre.8
> 
> ### Environment
> * OS:Android (HTC - Oculus VR Devices)
> * Unity version:6000.0.49f1
> ### Steps To Reproduce
> ```
> 1.	Create a Unity project (tested with Unity 6000.0.49f1).
> 2.	Install com.unity.webrtc package with different versions: pre.4, pre.6, and pre.8.
> 3.	Set up a simple video streaming scenario using VideoStreamTrack to stream a RenderTexture from VR device (Oculus/HTC Vive Focus, OpenXR, Vulkan backend).
> 4.	Start WebRTC signaling and establish peer connection successfully.
> 5.	Once the video stream starts, observe behavior on each version.
> ```
> 
> ### Current Behavior
> ```
> •	✅ In 3.0.0-pre.4: Streaming works fully stable, video frames are continuously streamed, no crashes or rendering issues observed.
> •	⚠ In 3.0.0-pre.6: Streaming starts, first frames are correctly sent, but the application crashes after 1–5 seconds randomly. Sometimes crashes after first frame, sometimes after a few seconds.
> •	❌ In 3.0.0-pre.8: Streaming never starts, VideoStreamTrack creation fails immediately or rendering crashes instantly. In some cases, encoder context is not fully initialized before first frame delivery.
> ```
> 
> All versions successfully complete peer connection, signaling, and ICE negotiation. The problem is purely at the rendering/encoder binding level after the video streaming starts.
> 
> On Unity Editor all versions successfully complete peer connection, signaling, and ICE also **Video Streaming**. It seems like the problem comes with the version update only affects Android devices.
> 
> ### Expected Behavior
> ```
> •	VideoStreamTrack should continue streaming frames consistently after the connection is established, without random crashes.
> •	Encoder binding should behave identically across all 3.x versions.
> •	New versions (pre.6 and later) should maintain compatibility with rendering stability that was working properly in pre.4.
> ```
> 
> ### Anything else?
> Issue fully reproduces even when using Unity Render Streaming package (which internally uses com.unity.webrtc as its core dependency). • Same behavior is observed on Render Streaming package: • When Render Streaming uses WebRTC 3.0.0-pre.8 or pre.6, identical crashes occur (either immediately or a few seconds after starting the video stream). • After downgrading Render Streaming’s internal WebRTC package to 3.0.0-pre.4, streaming works fully stable. • This strongly suggests the root cause is inside the WebRTC package itself, and affects any downstream solution that builds on top of it.

@merttalhayener There's a workaround to this: if you rebuild the plugin with EXPORT_HANDLE = false in VulkanTexture2D::Init function, it works just fine.  Here's the Android plugin I built and tested today: https://drive.google.com/file/d/1XjR22tsAEgUVhp5E5JvPJPrBkH8iPgeU/view?usp=sharing
@karasusan It seems that with EXPORT_HANDLE = true it fails to Allocate Memory in vkAllocateMemory(VulkanUtility.cpp), most probably due to External Memory Handle Type being set as VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR in VulkanUtility.cpp, even for Android.

**Comment by merttalhayener** [comment]
> > ### Package version
> > 3.0.0-pre.8
> > ### Environment
> > 
> > * OS:Android (HTC - Oculus VR Devices)
> > * Unity version:6000.0.49f1
> > 
> > ### Steps To Reproduce
> > ```
> > 1.	Create a Unity project (tested with Unity 6000.0.49f1).
> > 2.	Install com.unity.webrtc package with different versions: pre.4, pre.6, and pre.8.
> > 3.	Set up a simple video streaming scenario using VideoStreamTrack to stream a RenderTexture from VR device (Oculus/HTC Vive Focus, OpenXR, Vulkan backend).
> > 4.	Start WebRTC signaling and establish peer connection successfully.
> > 5.	Once the video stream starts, observe behavior on each version.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Current Behavior
> > ```
> > •	✅ In 3.0.0-pre.4: Streaming works fully stable, video frames are continuously streamed, no crashes or rendering issues observed.
> > •	⚠ In 3.0.0-pre.6: Streaming starts, first frames are correctly sent, but the application crashes after 1–5 seconds randomly. Sometimes crashes after first frame, sometimes after a few seconds.
> > •	❌ In 3.0.0-pre.8: Streaming never starts, VideoStreamTrack creation fails immediately or rendering crashes instantly. In some cases, encoder context is not fully initialized before first frame delivery.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All versions successfully complete peer connection, signaling, and ICE negotiation. The problem is purely at the rendering/encoder binding level after the video streaming starts.
> > On Unity Editor all versions successfully complete peer connection, signaling, and ICE also **Video Streaming**. It seems like the problem comes with the version update only affects Android devices.
> > ### Expected Behavior
> > ```
> > •	VideoStreamTrack should continue streaming frames consistently after the connection is established, without random crashes.
> > •	Encoder binding should behave identically across all 3.x versions.
> > •	New versions (pre.6 and later) should maintain compatibility with rendering stability that was working properly in pre.4.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Anything else?
> > Issue fully reproduces even when using Unity Render Streaming package (which internally uses com.unity.webrtc as its core dependency). • Same behavior is observed on Render Streaming package: • When Render Streaming uses WebRTC 3.0.0-pre.8 or pre.6, identical crashes occur (either immediately or a few seconds after starting the video stream). • After downgrading Render Streaming’s internal WebRTC package to 3.0.0-pre.4, streaming works fully stable. • This strongly suggests the root cause is inside the WebRTC package itself, and affects any downstream solution that builds on top of it.
> 
> [@merttalhayener](https://github.com/merttalhayener) There's a workaround to this: if you rebuild the plugin with EXPORT_HANDLE = false in VulkanTexture2D::Init function, it works just fine. Here's the Android plugin I built and tested today: https://github.com/himanchalsharmaa/UnityWebrtcQuestVulkanFix/tree/master/Runtime/Plugins/Android [@karasusan](https://github.com/karasusan) It seems that with EXPORT_HANDLE = true it fails to Allocate Memory in vkAllocateMemory(VulkanUtility.cpp), most probably due to External Memory Handle Type being set as VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR in VulkanUtility.cpp, even for Android.

Yes, when I tested with the Android plugin you sent, the video was successfully transmitted to the other side without any issues. Thank you for getting to the root of the problem and reporting it to the developers—hopefully, they will release an update regarding this soon.

**Comment by AlexRadacki** [comment]
We've created an issue about this, and had it verified:

https://issuetracker.unity3d.com/issues/android-vulkan-the-video-is-not-streamed-when-it-is-added-with-rtcrtpsender-dot-addtrack-method

Please vote it up, to push the importance - thanks!

**Comment by himanchalsharmaa** [comment]
> > > We've created an issue about this, and had it verified:
> > > https://issuetracker.unity3d.com/issues/android-vulkan-the-video-is-not-streamed-when-it-is-added-with-rtcrtpsender-dot-addtrack-method
> > > Please vote it up, to push the importance - thanks!
> > 
> > 
> > Voted. Although, you're better off using the custom link. I had built that because of another optimization bug(https://issuetracker.unity3d.com/issues/quest-gles3-transparent-materials-disappear-due-to-fullscreenrenderpass-on-quest-when-multiview-slash-spi-is-used-with-msaa-on-opengles3) that they've still not fixed. And that one is far major and current . This project is most probably dead : [#1084](https://github.com/Unity-Technologies/com.unity.webrtc/issues/1084)
> 
> Do you know of a maintained fork ob the webrtc package? I'm using it for pretty everything RTC related [SimpleWebRTC](https://github.com/FireDragonGameStudio/SimpleWebRTC) and even expanded it to work with web clients [SimpleWebRTC-Web](https://github.com/FireDragonGameStudio/SimpleWebRTC-Web). Currently working on a WebRTC based "cross-platform spectator app" and already ran into multiple issues. Oo

I don't know of anything being actively maintained. Your best bet is to build it yourself(the package has build scripts).  For your issue(https://github.com/Unity-Technologies/com.unity.webrtc/issues/1087), it doesn't look like the plugin needs rebuilding . 
Instead of going via package manager, just put the runtime folder(https://github.com/Unity-Technologies/com.unity.webrtc/tree/5f873f2ac17f3514ffe8a8514e94bff5e93e3982/Runtime) in your Assets and modify the resolution in Webrtc.cs as you pointed out.

**Comment by sidovrelax** [comment]
We are encountering the same issue and were able to resolve it using the proposed fix here: [UnityWebrtcQuestVulkanFix](https://github.com/himanchalsharmaa/UnityWebrtcQuestVulkanFix/tree/master/Runtime/Plugins/Android). However, we would strongly prefer to rely on the official package. Is there a way to contribute and help move this fix into a full release?

We are relying heavily on the WebRTC developments in Unity for our app and would really like to contribute to and actively help maintain this package.

Additionally, we are working with the Pico G3 platform, which is currently crashing due to memory allocation issues even with the fix applied. Once we have a solution, would it be possible to contribute that back to the main package as well?

**Comment by himanchalsharmaa** [comment]
I think it has been officially fixed as of this commit
https://github.com/Unity-Technologies/com.unity.webrtc/pull/1092.
Just taking a fresh build without any changes works.

**Comment by himanchalsharmaa** [comment]
You have to build the package(android plugin) with above-mentioned commit
first. Latest binaries aren't in releases(as of now).

**Comment by FireDragonGameStudio** [comment]
Just wanted to give a big Thank you! to @karasusan Tested Vulkan builds on my Quest3 and Pixel phone and it worked like a Charm! 🥳

**Comment by AlexRadacki** [comment]
> Just wanted to give a big Thank you! to [@karasusan](https://github.com/karasusan) Tested Vulkan builds on my Quest3 and Pixel phone and it worked like a Charm! 🥳

Great news! Just to confirm: Did it work right out of the box with the latest package version v3.0.0, or was a modification necessary?

**Comment by Justin-VRelax** [comment]
Hey all,

We are having some trouble (stuck for a few weeks) with the integration for some VR targets.

The fix for this issue actually allowed us to see it work for the first time on the **Meta Quest 3**, **Meta Quest 3S** and **PICO 4**.
However, we are still encountering issues on **PICO G3** and **PICO Neo3** headsets which are crucial release targets for us.

Here we are encountering the issue that it crashes on launch, we have tried a "fork" where the startup hooks were disabled. This allowed the app to start, but we were unable to get the connection working, we assume because of this issue that has now been fixed?

Does someone happen to have a fork where both this fix and the startup hooks solutions are combined? Or any other experience with related to WebRTC for the mentioned headsets? All help is appreciated!

**Comment by FireDragonGameStudio** [comment]
> Hey all,
> 
> We are having some trouble (stuck for a few weeks) with the integration for some VR targets.
> 
> The fix for this issue actually allowed us to see it work for the first time on the **Meta Quest 3**, **Meta Quest 3S** and **PICO 4**.
> However, we are still encountering issues on **PICO G3** and **PICO Neo3** headsets which are crucial release targets for us.
> 
> Here we are encountering the issue that it crashes on launch, we have tried a "fork" where the startup hooks were disabled. This allowed the app to start, but we were unable to get the connection working, we assume because of this issue that has now been fixed?
> 
> Does someone happen to have a fork where both this fix and the startup hooks solutions are combined? Or any other experience with related to WebRTC for the mentioned headsets? All help is appreciated!


Hi, have you tried V3.0.0, which is currently only installable via package manager git link? I was playing around with my asset SimpleWebRTC and it worked quite well. Not quite sure if PICO G3 and PICO Neo3 work with Vulkan builds btw 🤔

**Comment by Justin-VRelax** [comment]
> Hi, have you tried V3.0.0, which is currently only installable via package manager git link? I was playing around with my asset SimpleWebRTC and it worked quite well. Not quite sure if PICO G3 and PICO Neo3 work with Vulkan builds btw 🤔

Yes, the v3.0.0 (git URL import) is what we are working with right now. This is where we got to see results for the other platforms.

With "Not quite sure if the platforms work with Vulkan builds", do you mean in general if these headsets would work with the Vulkan Graphics API? We have been using Vulkan on these headsets for quite some time.

I have read somewhere that it could be caused by the app loading the webrtc package at startup before vulkan initialization is ready for it. We can confirm that just the presence of the com.unity.webrtc package is causing the crashes on these platforms.

Both G3 and Neo3 have similar logging to this, This is from a G3 specifically:
```
2025/09/26 14:56:33.098 754 754 Fatal DEBUG backtrace:
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #00 pc 00000000000b8480  /vendor/lib64/hw/vulkan.kona.so (qglinternal::vkCreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+1128) (BuildId: f8caf8bf35d3f1bd8bcde8949f10d29e)
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #01 pc 000000000001abb8  /system/lib64/libvulkan.so (vulkan::driver::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+800) (BuildId: 22676fcba6e455c2a8f2fe06e97c3dfe)
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #02 pc 0000000000012d3c  /system/lib64/libvulkan.so (vulkan::api::CreateInstance(VkInstanceCreateInfo const*, VkAllocationCallbacks const*, VkInstance_T**)+3368) (BuildId: 22676fcba6e455c2a8f2fe06e97c3dfe)
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #03 pc 00000000001305ac  /data/app/com.vrelax.vr.pico.g3-RqhpdBAo_trYs0P3OUS1Ug==/lib/arm64/libwebrtc.so
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #04 pc 0000000000e3b0bc  /data/app/com.vrelax.vr.pico.g3-RqhpdBAo_trYs0P3OUS1Ug==/lib/arm64/libunity.so!libunity.so (offset 0x516000) (BuildId: cd62e6e0f1471e38)
2025/09/26 14:56:33.098 754 754 Fatal DEBUG       #05 pc 000000000100000a  <unknown>
```

I was hoping someone involved in this issue might have experience with these headsets as well. Otherwise, I will create a separate issue for this.

**Comment by himanchalsharmaa** [comment]
Same isse - https://github.com/Unity-Technologies/com.unity.webrtc/issues/437 ? @Justin-VRelax

**Comment by Justin-VRelax** [comment]
> Same isse - [#437](https://github.com/Unity-Technologies/com.unity.webrtc/issues/437) ? [@Justin-VRelax](https://github.com/Justin-VRelax)

Yes, especially the latest comments look like an exact match!
Thank you, I will continue my efforts there.

**Comment by dakahler** [comment]
@Justin-VRelax were you able to find any solution to the startup crash?

**Comment by devvrelax** [comment]
Hey @dakahler!
No, we have been unable to find a maintainable solution. We have directed our attention towards an alternative way of integrating WebRTC techniques for our use case.

I don't want to "advertise" that alternative here, so feel free to reach out more directly. I'm happy to share our insights.
